### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by thehydroimpulse** [thehydroimpulse/nanomsg.rs#29]
A meta-issue for the refactor of this library that will focus on a few main things:
- A safe idiomatic Rust API
- A separate, low-level package containing only the bindings to nanomsg.
- Lots and lots of tests!

Right now, the library is fairly ugly, with barely any tests, super non-idiomatic and most likely unsafe to use.

Todo:
- [x] #28 Create a new package `libnanomsg` for the bindings.
- [x] Create some basic tests to ensure the bindings work correctly and we're not segfaulting or anything.
- [x] Create a `result` module that will contain the new `NanoResult` and `NanoError` types.
- [x] Create a `socket` module that will be the high-level API for working with nanomsg sockets.
- [x] Create a `protocol` module that will hold a `Protocol` enum with the various different protocols.

Some ideas for the socket API:

``` rust
use nanomsg::{Socket, Req, Rep};

spawn(proc() {
    let mut socket = match Socket::new(Rep) {
        Ok(socket) => socket,
        Err(err) => fail!("{}", err)
    };

    match socket.bind("tcp://*:6789") {
        Ok(()) => {},
        Err(err) => fail!("{}", err)
    }

    socket.read();   
});

let mut client = Socket::new(Req);
client.bind("tcp://*:6789");
client.send("shutdown");
```
